name: build-and-push-latest-docker-image

on:
  push:
    branches:
      - "master"
      - "docker"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: exporter-go
          push: false
          tags: mcelep/opa_scorecard_exporter:latest
